name: release

on:
  workflow_dispatch:

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - rust_target: x86_64-unknown-linux-gnu
            artifact_name: code-to-md-linux-amd64
          - rust_target: x86_64-pc-windows-gnu
            artifact_name: code-to-md-windows-amd64.exe

    steps:
      - name: checkout code
        uses: actions/checkout@v4

      - name: Set up Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable
          target: ${{ matrix.rust_target }}

      - name: Install mingw for Windows cross-compilation
        if: matrix.rust_target == 'x86_64-pc-windows-gnu'
        run: sudo apt-get install -y mingw-w64

      - name: Build the binary
        run: |
          cargo build --release --target ${{ matrix.rust_target }}
          if [[ "${{ matrix.artifact_name }}" == *.exe ]]; then
            mv target/${{ matrix.rust_target }}/release/code-to-md.exe ${{ matrix.artifact_name }}
          else
            mv target/${{ matrix.rust_target }}/release/code-to-md ${{ matrix.artifact_name }}
          fi

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.artifact_name }}
          path: ${{ matrix.artifact_name }}
